# Generated by Django 5.0.3 on 2024-03-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questhub_app', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='place',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
