# Generated by Django 5.0.3 on 2024-03-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questhub_app', '0004_registerprofile_bio_registerprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
